spin_manifest_version = 2

[application]
name = "http-out"
version = "1.0.0"
authors = ["Jora Troosh <tensorush@gmail.com>"]
description = "Example application that sends an outbound HTTP request."

[[trigger.http]]
route = "/..."
component = "http-out"

[component.http-out]
source = "../../zig-out/bin/http-out.wasm"
allowed_outbound_hosts = [
    "https://postman-echo.com",
    "https://random-data-api.fermyon.app",
]

[component.http-out.build]
workdir = "../../"
command = "zig build example"
